server:
  port: 9000
  
  
spring:
  security:
    oauth2:
      client:
        registration:
          sample-auth:
            provider: okta      
            client-id: 
            client-secret: 
            redirect-uri : http://localhost:9000/login/oauth2/code/sample-auth
            scope: openid, profile, email
            authorization-grant-type: authorization_code
          client-a:            
            provider: okta      
            client-id: 
            client-secret:       
            redirect-uri : http://localhost:9000/service-a
            scope: authority-a
            authorization-grant-type: authorization_code
          github-client:
            provider: github      
            client-id: 
            client-secret:       
            redirect-uri : http://localhost:9000/login/oauth2/code/github-client
            scope: user, repo
            authorization-grant-type: authorization_code                           
        provider:
          okta:
            issuer-uri: https://tcs-karthikbashyam.okta.com/oauth2/default
            #With issuer-uri no need to configure the below 3 props.
            #authorization-uri: https://tcs-karthikbashyam.okta.com/oauth2/default/v1/authorize
            #token-uri: https://tcs-karthikbashyam.okta.com/oauth2/default/v1/token
            #user-info-uri: https://tcs-karthikbashyam.okta.com/oauth2/default/v1/userinfo 
          github: 
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
#   resource:
#      userInfoUri: https://api.github.com/user
#      prefer-token-info : false