server:
  port: 9000

spring:
  security:
    oauth2:
      client:
        registration:
          sample-auth:
            provider: keycloak      
            client-id: sample-openid
            client-secret: bda9fd76-d6e5-4131-9924-89a72629fd69
            redirect-uri: http://localhost:9000/login/oauth2/code/sample-auth
            scope: openid
            authorization-grant-type: authorization_code            
        provider:
          keycloak:
            authorization-uri: http://localhost:8080/auth/realms/dev/protocol/openid-connect/auth
            token-uri: http://localhost:8080/auth/realms/dev/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/auth/realms/dev/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8080/auth/realms/dev/protocol/openid-connect/certs            
             
resource-uri: https://api.github.com/users/KarthikBashyam/repos