server:
  port: 9000

spring:
  security:
    oauth2:
      client:
        registration:
          github-client:
            provider: github      
            client-id: 
            client-secret: 
            redirect-uri: http://localhost:9000/login/oauth2/code/github-client
            scope: user,repo
            authorization-grant-type: authorization_code
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
             
resource-uri: https://api.github.com/users/KarthikBashyam/repos